language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
git:
  submodules: false
env:
  - FLASK_ENV=ci

before_install:
  # Use sed to replace the SSH URL with the public HTTP URL
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # Manually initialize submodules
  - git submodule update --init --recursive
  - pip install pipenv
before_script:
  - script/setup
script:
  - script/cibuild
