language: python
python:
  - "3.6"
before_install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
before_script:
  - psql -c 'create database requests_queue_ci;' -U postgres
  - pipenv run alembic upgrade head
script:
  - python -m pytest
services:
  - postgresql
env:
  - FLASK_ENV=ci
addons:
  postgresql: "9.6"
