version: '3'

services:
  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=requests_queue
    ports:
      - "5432:5432"
