"""add sequence to status events

Revision ID: 1a0dc6187f19
Revises: 4c0289c9a8ad
Create Date: 2018-07-09 16:39:28.381954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0dc6187f19'
down_revision = '4c0289c9a8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_events', sa.Column('sequence', sa.BigInteger(), nullable=False))
    op.drop_constraint('status_events_request_id_fkey', 'status_events', type_='foreignkey')
    op.create_foreign_key('status_events_request_id_fkey', 'status_events', 'requests', ['request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    db = op.get_bind()
    db.execute("CREATE SEQUENCE status_events_sequence_seq OWNED BY status_events.sequence;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('status_events_request_id_fkey', 'status_events', type_='foreignkey')
    op.create_foreign_key('status_events_request_id_fkey', 'status_events', 'requests', ['request_id'], ['id'])
    op.drop_column('status_events', 'sequence')
    # ### end Alembic commands ###

    db = op.get_bind()
    db.execute("DROP SEQUENCE status_events_sequence_seq;")
